name: Build C/C++ Program

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Compile HelloWorld.c
      uses: gcc HelloWorld.c -o HelloWorld.exe

    - name: Run HelloWorld
      uses: ./HelloWorld.exe

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
