name: Build C/C++ Program for Pynq Z2

on:
  push:
    branches:
      - main  # Change this to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Xilinx tools
      run: |
        wget -q https://github.com/Xilinx/PYNQ/releases/download/v2.6/arm-linux-gnueabi.tar.gz
        tar -xvf arm-linux-gnueabi.tar.gz -C $HOME
        export PATH="$HOME/gcc-arm-linux-gnueabi/bin:$PATH"
        arm-linux-gnueabihf-gcc --version
      shell: bash

    - name: Build Program
      run: |
        if [[ -f HelloWorld.c ]]; then
          arm-linux-gnueabihf-gcc HelloWorld.c -o HelloWorld
        elif [[ -f HelloWorld.cpp ]]; then
          arm-linux-gnueabihf-g++ HelloWorld.cpp -o HelloWorld
        else
          echo "No C/C++ source file found."
          exit 1
        fi
      shell: bash

    - name: Run Program on Pynq Z2 (if applicable)
      run: |
        # If you have a way to transfer the compiled program to the Pynq Z2 and run it, do so here.
        # For example, using SCP to copy the executable to the board.
        # sshpass -p 'password' scp HelloWorld root@pynq_z2_ip:/path/on/board
      shell: bash
