name: Compile C++ for TUL Pynq Z2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up C++ Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ g++-arm-linux-gnueabihf

      - name: Compile C++ code for x86
        run: g++ HelloWorld.cpp -o HelloWorld.exe 

      - name: Compile C++ code for ARM
        run: arm-linux-gnueabihf-g++ HelloWorld.cpp -o HelloWorld-arm

      - name: Run Executable
        run: ./HelloWorld.exe

      - name: Run ARM Executable in Docker Container
        run: docker run -v $(pwd):/mnt --rm multiarch/qemu-user-static --reset -p yes --credential yes /usr/bin/qemu-arm-static -L /usr/arm-linux-gnueabihf /mnt/HelloWorld-arm
