name: Build C/C++ Program for TUL Pynq Z2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up C/C++ environment
      uses: actions/setup-cpp@v2

    - name: Install Cross-Compiler
      run: |
        # Replace 'cross-compiler-command' with the appropriate installation command
        sudo apt-get install -y cross-compiler-command
      shell: bash

    - name: Cross-Compile for TUL Pynq Z2
      run: |
        # Replace 'program_name' with your program's filename
        # Replace 'cross-compile-command' with the cross-compiler command
        cross-compile-command program_name.cpp -o program_name
      shell: bash
      working-directory: ./path/to/your/code

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: program
        path: ./path/to/your/code/program_name
