name: Compile C++ for TUL Pynq Z2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install cross-compiler
        run: sudo apt-get update && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Compile C++ code
        run: arm-linux-gnueabihf-g++ main.cpp -o main-arm

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-code
          path: main-arm
